In [37]:
import torch
import pandas as pd

# Load CSV and skip the first row (column names)
df = pd.read_csv("data.csv", skiprows=1, header=None)

# Extract observations (remove `player1_action` at index 7 and `player2_action` at index 8)
obs_data = df.drop(columns=[8, 9])  

# Convert to PyTorch tensor
obs_tensor = torch.tensor(obs_data.values, dtype=torch.float32)

# Save observations
torch.save(obs_tensor, "fighting_data.pt")

print("✅ Observations saved as 'fighting_data.pt'")




✅ Observations saved as 'fighting_data.pt'


In [31]:
# Extract only `player1_action`
action_data = df[9]  

# Convert to PyTorch tensor
action_tensor = torch.tensor(action_data.values, dtype=torch.long)  # Long for classification

# Save actions
torch.save(action_tensor, "action_data.pt")

print("✅ Actions saved as 'action_data.pt'")


✅ Actions saved as 'action_data.pt'


In [38]:
# Load tensors
obs_data = torch.load("fighting_data.pt")
action_data = torch.load("action_data.pt")

print(f"🟢 Observations Shape: {obs_data.shape}")  # Should be (num_samples, 8)
print(f"🟠 Actions Shape: {action_data.shape}")  # Should be (num_samples,)
print(f"🔍 First 5 Observations:\n{obs_data[:20]}")
print(f"🎯 First 5 Actions:\n{action_data[:20]}")


🟢 Observations Shape: torch.Size([12822, 8])
🟠 Actions Shape: torch.Size([12822])
🔍 First 5 Observations:
tensor([[0.1250, 0.8125, 0.1420, 0.0000, 0.8750, 0.8125, 0.1420, 0.0000],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
        [0.1250, 0.8125, 0.1420, 0.0104, 0.8750, 0.8125, 0.1420, 0.0104],
      

C:\Users\nived\AppData\Local\Temp\ipykernel_9312\1645062557.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  obs_data = torch.load("fighting_data.pt")
C:\Users\nived\AppD

In [18]:
import torch.optim as optim
import torch.nn as nn
from stable_baselines3 import PPO

In [20]:
ppo_model = PPO.load("ppo_streetfighter2.zip")
optimizer = optim.Adam(ppo_model.policy.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss() 
num_epochs = 5
batch_size = 32

e:\collage\s7\reproject\.venv\lib\site-packages\stable_baselines3\common\save_util.py:449: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  th_object = th.load(file_content, ma

In [ ]:

action_data = action_data.long()
for epoch in range(num_epochs):
    total_loss = 0
    for i in range(0, len(obs_data), batch_size):
        optimizer.zero_grad()

        # Mini-batch sampling
        batch_obs = obs_data[i : i + batch_size]  # Get batch of observations
        batch_actions = action_data[i : i + batch_size]  # Get batch of actions

        # Forward pass (PPO policy)
        predicted_actions, _, _ = ppo_model.policy(batch_obs)

        # Compute loss
        loss = criterion(predicted_actions, batch_actions)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"🔥 Epoch {epoch+1}/{num_epochs}, Loss: {total_loss:.4f}")

RuntimeError: Expected floating point type for target with class probabilities, got Long

In [81]:
import torch
import torch.nn as nn
import torch.optim as optim
from stable_baselines3 import PPO

# Load PPO model
ppo_model = PPO.load("ppo_streetfighter1")

# Load observation & action datasets
obs_data = torch.load("fighting_data.pt")   # Observations (states)
action_data = torch.load("action_data.pt")  # Actions

# Ensure correct tensor types
obs_data = obs_data.float()        # Observations should be float32
action_data = action_data.long()   # Actions should be int64 for CrossEntropyLoss

# Define loss function & optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(ppo_model.policy.parameters(), lr=1e-4)

# Get number of possible actions
num_classes = 8  # Adjust if needed

# Training loop
num_epochs = 5

for epoch in range(num_epochs):
    for obs, action in zip(obs_data, action_data):
        obs = obs.unsqueeze(0)  # Ensure it has a batch dimension
        action = action.unsqueeze(0)  # Ensure it has a batch dimension
        
        # Forward pass
        predicted_action_logits, _, _ = ppo_model.policy(obs)

        # Compute loss
        loss = criterion(predicted_action_logits, action)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")

# Save the updated model
ppo_model.save("ppo_streetfighter_bc")
print("✅ Training complete! Model saved as ppo_streetfighter_bc")


C:\Users\nived\AppData\Local\Temp\ipykernel_9312\2617039872.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  obs_data = torch.load("fighting_data.pt")   # Observations (

RuntimeError: Expected floating point type for target with class probabilities, got Long

In [117]:
import torch
import torch.nn as nn
import torch.optim as optim
from stable_baselines3 import PPO

# Load PPO model
ppo_model = PPO.load("ppo_streetfighter1")

# Load observation & action datasets
obs_data = torch.load("fighting_data.pt")   # Observations (states)
action_data = torch.load("action_data.pt")  # Actions

# Ensure correct tensor types
obs_data = obs_data.float()        # Observations should be float32
action_data = action_data.long()   # Actions should be int64 for CrossEntropyLoss

# Define loss function & optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(ppo_model.policy.parameters(), lr=1e-4)

# Get number of possible actions
num_classes = 8  # Adjust if needed

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    for obs, action in zip(obs_data, action_data):
        obs = obs.unsqueeze(0)  # Ensure it has a batch dimension
        action = action.unsqueeze(0)  # Ensure it has a batch dimension
        distribution = ppo_model.policy.get_distribution(obs)

        # Extract logits manually
        predicted_action_logits = distribution.distribution.logits  # SB3 stores it inside `.distribution`
        # Ensure action is a single index (not one-hot, not float)
        action = action.long().view(-1)  # Shape: [1]

        # Compute loss
        loss = criterion(predicted_action_logits, action)   
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")
ppo_model.save("ppo_streetfighter_bc")
print("✅ Training complete! Model saved as ppo_streetfighter_bc")


C:\Users\nived\AppData\Local\Temp\ipykernel_9312\2061070428.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  obs_data = torch.load("fighting_data.pt")   # Observations (

Epoch 1/5, Loss: 3.9681


KeyboardInterrupt: 

In [116]:
import torch
import torch.nn as nn
import torch.optim as optim
from stable_baselines3 import PPO

# Load PPO model
ppo_model = PPO.load("ppo_streetfighter1")

# Load observation & action datasets
obs_data = torch.load("fighting_data.pt").float()  # Ensure float32 for obs
action_data = torch.load("action_data.pt").long()  # Ensure int64 for actions

# Define loss function & optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(ppo_model.policy.parameters(), lr=1e-3)  # Increased learning rate

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    for obs, action in zip(obs_data, action_data):
        obs = obs.unsqueeze(0)  # Ensure shape [1, obs_dim]
        action = action.view(1)  # Ensure shape [1]

        # Extract action distribution
        distribution = ppo_model.policy.get_distribution(obs)
        predicted_action_logits = distribution.distribution.logits  # Get logits

        # Compute loss
        loss = criterion(predicted_action_logits, action)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")

# Save the updated model
ppo_model.save("ppo_streetfighter_bc")
print("✅ Training complete! Model saved as ppo_streetfighter_bc")


C:\Users\nived\AppData\Local\Temp\ipykernel_9312\991034820.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  obs_data = torch.load("fighting_data.pt").float()  # Ensure f

Epoch 1/5, Loss: 4.3581
Epoch 2/5, Loss: 4.2550


KeyboardInterrupt: 

In [111]:
# Get action logits directly from the model's forward pass
predicted_action_logits, _, _ = ppo_model.policy.forward(obs)

print("Predicted logits shape:", predicted_action_logits.shape)
print(predicted_action_logits)


Predicted logits shape: torch.Size([1])
tensor([7])


In [110]:
# Get distribution
distribution = ppo_model.policy.get_distribution(obs)

# Extract logits manually
predicted_action_logits = distribution.distribution.logits  # SB3 stores it inside `.distribution`

print("Predicted logits shape:", predicted_action_logits.shape)
print(predicted_action_logits)
# Ensure action is a single index (not one-hot, not float)
action = action.long().view(-1)  # Shape: [1]

# Compute loss
loss = criterion(predicted_action_logits, action)

print("Loss:", loss.item())  # Debugging


Predicted logits shape: torch.Size([1, 8])
tensor([[-3.7262, -3.8732, -3.6110, -4.1301, -3.6445, -3.6774, -4.0116, -0.1714]],
       grad_fn=<SubBackward0>)
Loss: 4.011620044708252


In [100]:
ppo_model.policy(obs)

(tensor([7]),
 tensor([[42.8937]], grad_fn=<AddmmBackward0>),
 tensor([-0.1714], grad_fn=<SqueezeBackward1>))

In [ ]:
action = action.long()
print(action.shape)  # Should be [1] for a single sample
print(action.dtype)  # Should be torch.int64 (Long)

torch.Size([1])
torch.int64


In [ ]:
print(predicted_action_logits.shape)  # Should be [1, num_classes]
print(predicted_action_logits.dtype)  # Should be torch.float32

torch.Size([12822])
torch.float32
